### ISSUE TITLE
Edit Command Bug

### ISSUE THREAD

**Issue by YShu7** [CS2103-AY1819S1-T12-4/main#115]
Incorrect error message: for index > list size + 1
<img width="309" alt="screen shot 2018-10-31 at 1 12 24 am" src="https://user-images.githubusercontent.com/35400815/47736766-58f80380-dcaa-11e8-98af-67e2f78c4f6d.png">

Block other commands: for index = list size + 1
<img width="343" alt="screen shot 2018-10-31 at 1 13 16 am" src="https://user-images.githubusercontent.com/35400815/47736795-6b723d00-dcaa-11e8-85b7-85a0684598d2.png">
Edit IssueList.length() + 1, in this case 2. The command won't execute and enter seems to be "switch to next line" instead a ENTER command. Therefore all the following command won't be executed after edit 2 ... is entered.

I circled some parts which may be relevant. I didn't test IssueLevel but based on the code, the same problem may occur.
 
<img width="1280" alt="screen shot 2018-10-31 at 1 10 29 am" src="https://user-images.githubusercontent.com/35400815/47737513-0ddef000-dcac-11e8-8006-7db9c9766e94.png">

**Comment by jasonvank** [comment]
thank you, fixed will pushed with my next PR
