### ISSUE TITLE
Edit command in solution level ? Directory problem ?

### ISSUE THREAD

**Issue by jasonvank** [CS2103-AY1819S1-T12-4/main#134]
Currently edit command has a standard format, 
`edit Index i/statement d/description t/tag`
`edit Index s/solutionlink r/remark`

Users can `select` the issue from the root directory, and also can `select` a solution to display the webpage. 
If a user is in the solution level, `root/issue 1/solution 2`, he is not allowed to edit link and remark (we didn't expect this before). If we allow editing in solution level, then edit command is unnecessary to have index then. It will have the third format. Not consistent anymore. Hence I may think we should allow the user to go back to the second level to edit. Selects a solution only for a webpage.

`root` - edit any issue description, remark or tag
`root/issue' - edit any solution link and remark
`root/issue/solution` - ? （go upper level, or allow to edit this solution, which has a third format)

Also if we display the directory information to a user, but we cannot go back to the second level directory from the third level but only can go home directory, is quite wierd.

**Comment by zhengwei143** [comment]
I think its fine?

 After `select SolutionIndex1`, `edit SolutionIndex2 ...` should change the values at `SolutionIndex2` and do a `select` as well to change to the other `Solution2`

`select solution` just has the function of displaying the link. Thoughts?

**Comment by jasonvank** [comment]
is it wired when you are in solution 2 (which directory will tell you are solution 2), but allow users to edit other solution?
anw, if it makes sense, I will change edit commands before the tutorial.

**Comment by zhengwei143** [comment]
It may be a bit weird, but maybe if we display the message properly it would be better, like maybe say something like "Currently viewing solution 2".

Or we could even do the autosuggest for commands - and suggest only the commands that can be called at each level. Let's discuss during tutorial tmr? As long as we make the changes by Friday 12pm should be fine.
