### ISSUE TITLE
GUI bugs

### ISSUE THREAD

**Issue by Swiftkage** [CS2103-AY1819S1-T12-4/main#144]

**Comment by Swiftkage** [comment]
1) Cannot access help window from GUI
2) Click to go to different issues does not work. From GUI, it is impossible to move from 1 issue to another
3) When user types invalid command, i think it is better to give an example eg. add i/JAVA_exception d/This is fatal error. tags should also be [tag]

**Comment by leo-1997** [comment]
CS2103T project is supposed to be stick a Command Line Project, so it is not necessary to click

**Comment by Swiftkage** [comment]
sry wrong place
