### ISSUE TITLE
Addtag occasionally does not display a tag after addtag (range)

### ISSUE THREAD

**Issue by zhengwei143** [CS2103-AY1819S1-T12-4/main#195]

**Comment by jasonvank** [comment]
>at 1-4 t/yes
sort tag
sort chro
at 1-3 t/good
undo
at 1-3 t/good
at 1-3 t/food

**Comment by jasonvank** [comment]
<img width="1433" alt="wechatimg557" src="https://user-images.githubusercontent.com/23273384/48208730-6c902200-e3ae-11e8-9e27-ae86b8075615.png">
It's inside the model but does not reflect on the UI.
