### ISSUE TITLE
add command after sorting tag (Issue order unpredictable)

### ISSUE THREAD

**Issue by leo-1997** [CS2103-AY1819S1-T12-4/main#199]

**Comment by jasonvank** [comment]
default data
————
>at 1-4 t/yes
sort tag
sort chro
at 1-3 t/good
undo
at 1-3 t/good
at 1-3 t/food

**Comment by jasonvank** [comment]
>clear
Y
add i/good d/hey
add i/good d/hey t/why
add i/good2 d/hey t/why
add i/good2 d/hey t/why t/meiyou
add i/good3 d/hey t/why t/meiyou
add i/good3 d/hey t/ t/meiyou
add i/good3 d/hey t/sd t/meiyou
add i/good4 d/hey t/sd t/meiyou
a i/good5 t/jason t/you
a i/good5 d/ hey t/jason t/you
sort tag
a i/good6 d/ hey t/jason
a i/good6 d/ hey
a i/good7 d/ hey
at 1 4 6 t/wenkai
undo
sort tag
at 1 4 6 t/wenkai



----
includes some invalid commands
