### ISSUE TITLE
Undo changed directory but UI doesn't reflect correctly

### ISSUE THREAD

**Issue by YShu7** [CS2103-AY1819S1-T12-4/main#203]
I use the default data.
Enter Command:
s 1
edit 1 r/remark
undo
<img width="1280" alt="screen shot 2018-11-09 at 9 15 03 pm" src="https://user-images.githubusercontent.com/35400815/48264464-8be98680-e464-11e8-91dd-2878ffa2a6a0.png">
This is because commit() is only called when an undoable command is called. In this case the first undoable command is edit, so the VersionedSaveIt that undo wants to roll back is initial version, whose Directory is root level.
I suggest post event DirectoryChangedEvent to change UI instead of trying to track the directory, because for me that means tracking all commands input.

**Comment by xllliu** [comment]
That's a good suggestion. I've made the change in the latest PR.
