### ISSUE TITLE
Some quick feedback for DG at mid-v1.4

### ISSUE THREAD

**Issue by eugenepeh** [CS2103-AY1819S1-T12-4/main#206]
* Doesn't seems to be updated
![image](https://user-images.githubusercontent.com/19277206/48276147-463bb680-e482-11e8-81a3-aa7e42258e90.png)
![image](https://user-images.githubusercontent.com/19277206/48276206-6c615680-e482-11e8-9f9c-cff045bd5ab1.png)
![image](https://user-images.githubusercontent.com/19277206/48276225-784d1880-e482-11e8-8987-c529a1ee193c.png)
* Problem areas spotted in diagrams
![image](https://user-images.githubusercontent.com/19277206/48276275-961a7d80-e482-11e8-88d3-d088d6e9945f.png)
![image](https://user-images.githubusercontent.com/19277206/48276306-a6325d00-e482-11e8-86a2-c19c8dded6ae.png)
![image](https://user-images.githubusercontent.com/19277206/48276347-be09e100-e482-11e8-8811-20c8eb3ecabe.png)
![image](https://user-images.githubusercontent.com/19277206/48276490-1640e300-e483-11e8-86d7-14dbe78b28c6.png)

Also, 4.3. Undo/Redo feature still showing all the examples as AB.
Lastly, you guys might want to include diagrams to better explain your features.

**Comment by leo-1997** [comment]
We will update it asap
